language: go
go:
 - 1.5.3
 - 1.6rc2
 - tip

matrix:
  allow_failures:
  - go: tip

install:
 - if [[ $TRAVIS_GO_VERSION == 1.5* ]]; then go get github.com/axw/gocov/gocov github.com/wadey/gocovmerge github.com/mattn/goveralls; fi

script:
 - make test
 # only run test-coverage for one go version
 - if [[ $TRAVIS_GO_VERSION == 1.5* ]]; then make test-coverage; $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci; fi
